### ISSUE TITLE
Unable to log in to UVO Unexpected error.

### ISSUE THREAD

**Issue by TD398** [wcomartin/kia_uvo#1]
I installed all the configuration files using samba into custom_components and doubled check to make sure the configuration was correct. 

I am able to find Kia UVO in the integrations but when I try to add it it asks me to authorize. So When I try to log in to my UVO account. I simply get a unexpected error. Here are the logs about the issue. 

  File "/config/custom_components/kia_uvo/config_flow.py", line 36, in async_step_user
    self.auth_info = await self.validate_authentication(user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 86, in validate_authentication
    await self.hass.async_add_executor_job(self.kia.login)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 44, in login
    self.auth = self.__login(self.username, self.password)
  File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 56, in __login
    return AuthToken(xhr['result']['accessToken'], xhr['result']['refreshToken'])

**Comment by holdestmade** [comment]
Same problem here

```
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 36, in async_step_user
    self.auth_info = await self.validate_authentication(user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 86, in validate_authentication
    await self.hass.async_add_executor_job(self.kia.login)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 44, in login
    self.auth = self.__login(self.username, self.password)
  File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 56, in __login
    return AuthToken(xhr['result']['accessToken'], xhr['result']['refreshToken'])
KeyError: 'result'
```

**Comment by Pyromancer579** [comment]
Hi,  I'm very new to coding (just two days in so far).

I've pip installed the KiaUvo modules and I'm just trying to run the first three lines of your code:

from KiaUvo import KiaUvo
client = KiaUvo(KIA_ID, KIA_PW)
client.get_vehicle_list()

I have defined the KIA_ID and KIA_PW earlier in my script, but I just get an error associated with the last line:

>>> 
======= RESTART: D:\Steves Stuff\Documents\Zappi-Powerwall\Kia Status.py =======
Traceback (most recent call last):
  File "D:\Steves Stuff\Documents\Zappi-Powerwall\Kia Status.py", line 28, in <module>
    client.get_vehicle_list()
  File "C:\Users\conta\AppData\Local\Programs\Python\Python38\lib\site-packages\KiaUvo\__init__.py", line 78, in get_vehicle_list
    raise InvalidAuthException
KiaUvo.InvalidAuthException
>>> 

I tried resetting my password on the Uvo App, but that didn't make any difference.

Am I doing something wrong, or is there a solution to allow me to move forward?

**Comment by HK-Moebius** [comment]
> Same problem here
> 
> ```
> Traceback (most recent call last):
>   File "/config/custom_components/kia_uvo/config_flow.py", line 36, in async_step_user
>     self.auth_info = await self.validate_authentication(user_input)
>   File "/config/custom_components/kia_uvo/config_flow.py", line 86, in validate_authentication
>     await self.hass.async_add_executor_job(self.kia.login)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 44, in login
>     self.auth = self.__login(self.username, self.password)
>   File "/usr/local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 56, in __login
>     return AuthToken(xhr['result']['accessToken'], xhr['result']['refreshToken'])
> KeyError: 'result'
> ```

also same problem!

**Comment by Voxxie** [comment]
Same issue here, (Europe) 
So maybe it is talking to the wrong servers?

**Comment by HK-Moebius** [comment]
Me also Europe (Germany)

**Comment by romix63** [comment]
Same issue here, (Europe - Italy)

**Comment by wcomartin** [comment]
Hey guys, sorry about that, I realized after I had written it that Kia and Hyundai use different APIs for different regions of the world, working on a international verison, currently this version only works for Canada
