### ISSUE TITLE
Installation hanging

### ISSUE THREAD

**Issue by agiuliano** [wcomartin/kia_uvo#3]
## Version of the custom_component

0.1.9

## Configuration

N/a

## Describe the bug

After following all the steps, I can see the Kia Uvo in my integrations but when I chose it, hassio hangs saying "Please wait while the integration is being installed" And waiting for 30 minutes id doesn't do anything. Checked the list of integration and it's not there. I've tried 3-4 times already

## Debug log

This is the only thing I see in logs core

```
2020-08-07 21:07:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Comment by agiuliano** [comment]
after rebooting the host a bunch of time I can finally see the login config window. Trying with my credentials (proven to work on the website) and I get

```
2020-08-08 11:34:17 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 36, in async_step_user
    self.auth_info = await self.validate_authentication(user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 86, in validate_authentication
    await self.hass.async_add_executor_job(self.kia.login)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/KiaUvo/__init__.py", line 44, in login
    self.auth = self.__login(self.username, self.password)
  File "/usr/local/lib/python3.8/site-packages/KiaUvo/__init__.py", line 56, in __login
    return AuthToken(xhr['result']['accessToken'], xhr['result']['refreshToken'])
KeyError: 'result'
```

**Comment by HK-Moebius** [comment]
The Integration works atm only for Canada. See https://github.com/wcomartin/kia_uvo/issues/1
hope this helps...

**Comment by Timple** [comment]
I suggest to keep #1 open or reflect the current status in the README.md this will save people from searching for solutions.

**Comment by wcomartin** [comment]
Readme Updated
